config/routes.rb
Rails.application.routes.draw do

  root 'pages#index'
  get 'about', to: 'pages#about'

  resources :posts
  resources :users, except: [:new]
  devise_for :users, path:'auth', path_names: { sign_in: 'login',
                                                sign_out: 'logout', sign_up: 'register'}

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ActiveRecord::Base

  belongs_to :user
  has_many :tag, dependent: :destroy
  accepts_nested_attributes_for :tag

  validates :user_id, presence: true
  validates :title, presence: true, length: { minimum: 3, maximum:50 }
  validates :description, presence: true, length: { minimum: 10, maximum: 300 }

  def tag_names
    tag.map(&:tag_name).join(',')
  end

  def tag_names=(tags)
    self.tag_attributes = tags.split(',').map do |tag|
      {tag_name: tag}
    end
  end

  def self.search(term)
    if term
      joins(:user, :tag).where('title LIKE ? or description Like ? or users.username LIKE ? or tags.tag_name LIKE ?',
            "%#{term}%", "%#{term}%", "%#{term}%", "%#{term}%").order('created_at DESC')
    else
      order('created_at DESC')
    end
  end


end

app/models/tag.rb
class Tag < ActiveRecord::Base

  belongs_to :post

  validates :tag_name, presence: true


end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :posts
  devise :database_authenticatable, :registerable

  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :username,
            presence: true,
            uniqueness: { case_sensitive: false },
            length: { minimum: 3, maximum: 25 }
  validates :email,
            presence: true,
            uniqueness: { case_sensitive: false},
            length: { maximum: 105 },
            format: { with: VALID_EMAIL_REGEX }
            before_save { self.email = email.downcase}
  validates :full_name,
            presence: true,
            length: { minimum: 3, maximum: 30 }
  validates :encrypted_password,
            presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index
  end

  def about
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.paginate(page: params[:page], per_page: 5).search(params[:term])
  end

  def new
    @post = Post.new
    @post.tag.build
  end

  def show
  end

  def create
    #render plain: params[:post].inspect
    @post = Post.new(post_params)
    @post.user = current_user

    if @post.save
      flash[:success] = "Post was successfully created!"
      redirect_to post_path(@post)
    else
      render 'new'
    end

  end

  def edit
    if @post.tag.count == 0
      @post.tag.build

    end
  end

  def update
    update_params = remove_tags
    if @post.update(update_params)
      flash[:success] = "Post was updated!"
      redirect_to post_path(@post)
    else
      flash[:success] = "Post was not updated"
      render 'edit'
    end
  end

  def destroy
    @post.destroy
    flash[:success] = "Post was deleted"
    redirect_to posts_path
  end

  private

    def post_params
      params.require(:post).permit(:title, :description, :tag_names, :term)
    end

    def set_post
      @post = Post.find(params[:id])
    end

    def remove_tags
      arr = params.require(:post).permit(:title, :description, :tag_names)
      new_tags = arr[:tag_names].split(',')
      old_tags = @post.tag.map(&:tag_name)

      del_tags = old_tags - new_tags
      update_tags = (new_tags - old_tags).join(',')

      del_tags.each do |tag|
        Tag.find_by_tag_name(tag).destroy
      end

      arr[:tag_names] = update_tags
      arr

    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authenticate_user!, only: [:index, :show, :edit, :update]

  def index
    @users = User.paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
    @user_posts = @user.posts.paginate(page: params[:page], per_page: 5)
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to Today I Have #{@user.username}"
      sign_in @user
      redirect_to posts_path
    else
      render 'users/registrations/new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Your account was updated successfully"
      redirect_to posts_path
    else
      render 'edit'
    end
  end

  private
    def user_params
      params.require(:user).permit(:username, :email, :full_name, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
module FormHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <%= link_to "Today I Have", root_path, class: "navbar-brand", id: "logo" %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

      <ul class="nav navbar-nav">
        <li><%= link_to "Posts", posts_path %></li>
        <% if user_signed_in? %>
          <li><%= link_to "Create Post", new_post_path %></li>
          <li><%= link_to "Users", users_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% end %>
          </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= debug(params) if Rails.env.development? %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= render 'shared/messages' %>
    <%= yield %>
  </body>
</html>

app/views/pages/about.html.erb
<h1>About This Practice Blog</h1>

<%= link_to 'Home', root_path %>

app/views/pages/index.html.erb
<h1>Welcome to the Practice Blog</h1>

<%= link_to 'About', about_path %>

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>

<div class="row">

  <div class="col-xs-12">
    <%= form_for(@post, :html => {class: "form-horizontal", role: "form"}) do |post_fields| %>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= post_fields.label :title %>
        </div>
        <div class="col-sm-6">
          <%= post_fields.text_field :title, class: "form-control", placeholder: "Title of Post", autofocus: true %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= post_fields.label :description %>
        </div>
        <div class="col-sm-6">
          <%= post_fields.text_area :description, rows: 10, class: "form-control", placeholder: "Body of Post" %>
        </div>
      </div>

      <div class="form-group">
        <div class="control-label col-sm-2">
          <%= post_fields.label :tag_names %>
        </div>
        <div class="col-sm-6">
          <%= post_fields.text_field :tag_names, class: "form-control", placeholder: "Post Tags" %>
        </div>
        <div class="col-sm-2">
          <p><b>Enter in the tags separated by commas</b></p>
        </div>
      </div>

      <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
          <%= post_fields.submit class: 'btn btn-primary btn-large' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Edit Post</h1>

<%= render 'form' %>
<div align="center">
  <%= link_to "Delete", post_path(@post), method: :delete, data: {
    confirm: "Are you sure you want to delete this article?"},
            class: "btn btn-xs btn-danger" %> |
  <%= link_to 'Back', posts_path, class: "btn btn-xs btn-success" %>
</div>

app/views/posts/index.html.erb
<h1 align="center">All Posts</h1>

<div align="center">
  <%= form_tag(posts_path, method: :get) do %>
    <%= text_field_tag :term, params[:term] %>
    <%= submit_tag 'Search', name: nil %>
    <%= link_to "Reset", posts_path %>
  <% end %>
</div>

<%= render 'shared/post', obj: @posts %>

<div align="center">
  <%= will_paginate %>
</div>

app/views/posts/new.html.erb
<h1>Create a new Post</h1>

<%= render 'form' %>
<div align="center">
  <%= link_to 'Back', posts_path, class: "btn btn-xs btn-success" %>
</div>

app/views/posts/show.html.erb
<h2 align="center">Title: <%= @post.title %></h2>
<div class="well col-xs-8 col-xs-offset-2">
  <% if @post.user %>
    <ul class="listing">
      <div class="row" align="center">
        <div class="col-md-4 col-md-offset-4">
          <li class="post-title"><%= link_to @post.user.username, user_path(@post.user) %></li>
          <li><small><%= pluralize(@post.user.posts.count, "post") if @post.user.posts %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <h4 class="center"><strong>Description:</strong></h4>
  <hr>
  <%= simple_format(@post.description) %>
  <p><b>Tags: </b>
    <i><% @post.tag.each do |tag| %>
        <%= tag.tag_name %>
        <% if tag != @post.tag.last %>
          <%= ',' %>
        <% end %>
      <% end %></i>
  </p>
  <br>
  <% if user_signed_in? && current_user.id == @post.user_id%>
    <%= link_to "Edit", edit_post_path(@post), class: "btn btn-xs btn-primary" %> |
    <%= link_to "Delete", post_path(@post), method: :delete, data: {
        confirm: "Are you sure you want to delete this article?"},
        class: "btn btn-xs btn-danger" %> |
  <% end %>
<%= link_to 'Back', posts_path, class: "btn btn-xs btn-success" %>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="panel panel-danger">
        <div class="panel-heading">
          <h2 class="panel-title">
            <%= pluralize(obj.errors.count, "error") %>
            prohibited this article from being saved:
          </h2>
          <div class="panel-body">
            <ul>
              <% obj.errors.full_messages.each do |msg|%>
                <li><%= msg %></li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/shared/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name, msg| %>
      <div class='alert alert-<%= "#{name}" %>'>
        <a href="#" class="close" data-dismiss="alert">&#215;</a>
        <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
      </div>
    <% end %>
  </div>
</div>

app/views/shared/_post.html.erb
<% obj.each do |post| %>
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="well well-1g">
        <div class="post-title">
          <%= link_to post.title, post_path(post) %>
        </div>
        <div class="post-body">
          <%= truncate(post.description, length:100) %>

          <p><b>Tags: </b>
            <i><% post.tag.each do |tag| %>
              <%= tag.tag_name %>
              <% if tag != post.tag.last %>
                <%= ',' %>
              <% end %>
            <% end %></i>
          </p>

          <div class="post-meta-details">
            <b><small>Created by: <%= post.user.username if post.user %>,
              <%= time_ago_in_words(post.created_at) %> ago,
              last updated: <%= time_ago_in_words(post.updated_at) %> ago</small></b>
          </div>
          <div class="post-actions">
            <% if user_signed_in? && current_user == post.user %>
              <%= link_to "Edit", edit_post_path(post), class:"btn btn-xs btn-primary" %>
              <%= link_to "Delete", post_path(post), method: :delete,
                        data: {confirm: "Are you sure you want to delete this article?"},
                        class: "btn btn-xs btn-danger" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/users/index.html.erb
<h1 align="center">All Users</h1>

<div align="center">
  <% @users.each do |user| %>
    <ul class="listing">
      <div class="row" align="center">
        <div class="well col-md-4 col-md-offset-4">
          <li class="post-title"><%= link_to user.username, user_path(user) %></li>
          <li><small><%= pluralize(user.posts.count, "post") if user.posts %></small></li>
        </div>
      </div>
    </ul>
  <% end %>
  <%= will_paginate %>
</div>

app/views/users/show.html.erb
<h1 align="center">Welcome to <%= @user.username  %>'s page</h1>

<h4 align="center"><%= @user.username %>'s posts</h4>

<%= render 'shared/post', obj: @user.posts %>

<div align="center">
  <%= will_paginate @user_posts %>
</div>